
name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - run: |
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
        env:
          SSH_KEY: ${{secrets.TEST}}
      - name: clone
        run: git clone git@github.com:peeweep-test/dde-dock.git
