
name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - run: |
          mkdir ~/.ssh
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
        env:
          SSH_KEY: ${{secrets.TEST}}
          KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
      - name: clone
        run: |
          git config -g user.user wurongjie
          git config -g user.email wurongjie@deepin.org
          git clone git@github.com:peeweep-test/dde-dock.git
          cd dde-dock
          date > test
          git commit -a -m "Test"
