
name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - uses: actions/github-script@v5
        with:
          script: |
            let checkNameGroup = "build"
            if(!checkNameGroup.startsWith("/")){
              checkNameGroup = '/' + checkNameGroup
            }
            console.log(checkNameGroup)
