name: Call build-distribution
on:
  push:
    paths-ignore:
      - ".github/workflows/**"
  pull_request_target:
    paths-ignore:
      - ".github/workflows/**"

jobs:
  check_job:
    uses: linuxdeepin/.github/.github/workflows/build-distribution.yml@master
    secrets:
      BUILD_GPG_PRIVATE_KEY: "1"
      BUILD_SSH_PRIVATE_KEY: "a"
      WEBDAV_PASSWD: "c"
      WEBDAV_USER: "d"
